{"num_games": 100, "student_agent_wins": [0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1], "random_agent_wins": [1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0], "student_agent_win_count": 25, "random_agent_win_count": 75, "student_agent_win_percentage": 0.25, "random_agent_win_percentage": 0.75, "student_agent_time_taken": 0.0037664151191711425, "random_agent_time_taken": 0.003294525146484375, "run_info": [{"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0040285587310791016, "random_agent_time": 0.0022106170654296875, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002608060836791992, "random_agent_time": 0.00269317626953125, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.004731893539428711, "random_agent_time": 0.002883434295654297, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003428459167480469, "random_agent_time": 0.001165151596069336, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00031495094299316406, "random_agent_time": 0.0009126663208007812, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002444028854370117, "random_agent_time": 0.002300262451171875, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0042362213134765625, "random_agent_time": 0.0014007091522216797, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.001913309097290039, "random_agent_time": 0.0029060840606689453, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.00374603271484375, "random_agent_time": 0.003778696060180664, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002633333206176758, "random_agent_time": 0.00595402717590332, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023736953735351562, "random_agent_time": 0.005094051361083984, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0025742053985595703, "random_agent_time": 0.0021474361419677734, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.006240129470825195, "random_agent_time": 0.008065462112426758, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004736661911010742, "random_agent_time": 0.007557868957519531, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00415492057800293, "random_agent_time": 0.0038328170776367188, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.01026296615600586, "random_agent_time": 0.008023500442504883, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002899169921875, "random_agent_time": 0.003400087356567383, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0036122798919677734, "random_agent_time": 0.002324342727661133, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026836395263671875, "random_agent_time": 0.0038940906524658203, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0029387474060058594, "random_agent_time": 0.0009834766387939453, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026068687438964844, "random_agent_time": 0.002423524856567383, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004433393478393555, "random_agent_time": 0.0052602291107177734, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0053937435150146484, "random_agent_time": 0.0058934688568115234, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025615692138671875, "random_agent_time": 0.0024361610412597656, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.003336191177368164, "random_agent_time": 0.00311279296875, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.003789186477661133, "random_agent_time": 0.0028123855590820312, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003183603286743164, "random_agent_time": 0.0030677318572998047, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.003687143325805664, "random_agent_time": 0.0030357837677001953, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0035958290100097656, "random_agent_time": 0.003068208694458008, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0026824474334716797, "random_agent_time": 0.0030286312103271484, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0002799034118652344, "random_agent_time": 0.002489805221557617, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005500316619873047, "random_agent_time": 0.0024487972259521484, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002965211868286133, "random_agent_time": 0.002794027328491211, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004597187042236328, "random_agent_time": 0.010048627853393555, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002756357192993164, "random_agent_time": 0.0023632049560546875, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0051403045654296875, "random_agent_time": 0.0023119449615478516, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0063190460205078125, "random_agent_time": 0.002193450927734375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005487918853759766, "random_agent_time": 0.0016853809356689453, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0018818378448486328, "random_agent_time": 0.0024716854095458984, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002375364303588867, "random_agent_time": 0.0020825862884521484, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003478527069091797, "random_agent_time": 0.0009210109710693359, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002438068389892578, "random_agent_time": 0.002510547637939453, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00661015510559082, "random_agent_time": 0.002118825912475586, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0039806365966796875, "random_agent_time": 0.0019423961639404297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004699230194091797, "random_agent_time": 0.006447792053222656, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0070302486419677734, "random_agent_time": 0.0025374889373779297, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.006496429443359375, "random_agent_time": 0.0019578933715820312, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004213809967041016, "random_agent_time": 0.002984285354614258, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0017957687377929688, "random_agent_time": 0.002691507339477539, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003103494644165039, "random_agent_time": 0.0021741390228271484, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005098104476928711, "random_agent_time": 0.00193023681640625, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00442051887512207, "random_agent_time": 0.0020399093627929688, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.00257110595703125, "random_agent_time": 0.0025479793548583984, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002931356430053711, "random_agent_time": 0.0032880306243896484, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005602598190307617, "random_agent_time": 0.005853891372680664, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004033327102661133, "random_agent_time": 0.001954317092895508, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0045812129974365234, "random_agent_time": 0.002057313919067383, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002780437469482422, "random_agent_time": 0.004499197006225586, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030357837677001953, "random_agent_time": 0.002775907516479492, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0041348934173583984, "random_agent_time": 0.006402015686035156, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004106760025024414, "random_agent_time": 0.0033903121948242188, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005552768707275391, "random_agent_time": 0.005316019058227539, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003072023391723633, "random_agent_time": 0.0027298927307128906, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00427699089050293, "random_agent_time": 0.005555391311645508, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004480123519897461, "random_agent_time": 0.003062725067138672, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.004755735397338867, "random_agent_time": 0.0027866363525390625, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003327608108520508, "random_agent_time": 0.002519845962524414, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003021240234375, "random_agent_time": 0.002141714096069336, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.003304719924926758, "random_agent_time": 0.002002716064453125, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0048656463623046875, "random_agent_time": 0.002822399139404297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00428318977355957, "random_agent_time": 0.0075016021728515625, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0025153160095214844, "random_agent_time": 0.0021660327911376953, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027353763580322266, "random_agent_time": 0.002259492874145508, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0002770423889160156, "random_agent_time": 0.0011835098266601562, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00235748291015625, "random_agent_time": 0.0031447410583496094, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022988319396972656, "random_agent_time": 0.0023963451385498047, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004517078399658203, "random_agent_time": 0.0034399032592773438, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004650592803955078, "random_agent_time": 0.0023179054260253906, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0048198699951171875, "random_agent_time": 0.002192974090576172, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004328727722167969, "random_agent_time": 0.003492593765258789, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00231170654296875, "random_agent_time": 0.0034389495849609375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00396418571472168, "random_agent_time": 0.0021698474884033203, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.0051097869873046875, "random_agent_time": 0.004639387130737305, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002686023712158203, "random_agent_time": 0.003214597702026367, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0046346187591552734, "random_agent_time": 0.00616765022277832, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024003982543945312, "random_agent_time": 0.003857851028442383, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023691654205322266, "random_agent_time": 0.0025212764739990234, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0047016143798828125, "random_agent_time": 0.0034894943237304688, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004683256149291992, "random_agent_time": 0.0021746158599853516, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.005315303802490234, "random_agent_time": 0.0063822269439697266, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003816843032836914, "random_agent_time": 0.004035234451293945, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0023598670959472656, "random_agent_time": 0.003157377243041992, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002437591552734375, "random_agent_time": 0.0020041465759277344, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.006330966949462891, "random_agent_time": 0.0023241043090820312, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004827737808227539, "random_agent_time": 0.0021359920501708984, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003950595855712891, "random_agent_time": 0.002132892608642578, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024220943450927734, "random_agent_time": 0.0027887821197509766, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005663394927978516, "random_agent_time": 0.00481867790222168, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0030260086059570312, "random_agent_time": 0.002534151077270508, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008129119873046875, "random_agent_time": 0.0068514347076416016, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}]}