{"num_games": 100, "student_agent_wins": [1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], "random_agent_wins": [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], "student_agent_win_count": 26, "random_agent_win_count": 74, "student_agent_win_percentage": 0.26, "random_agent_win_percentage": 0.74, "student_agent_time_taken": 0.00366246223449707, "random_agent_time_taken": 0.0030258846282958983, "run_info": [{"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00040650367736816406, "random_agent_time": 0.0010488033294677734, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0034520626068115234, "random_agent_time": 0.002742290496826172, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0025200843811035156, "random_agent_time": 0.0021123886108398438, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004740238189697266, "random_agent_time": 0.002418994903564453, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0028989315032958984, "random_agent_time": 0.0029108524322509766, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0059659481048583984, "random_agent_time": 0.002159595489501953, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0037047863006591797, "random_agent_time": 0.0027267932891845703, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005005598068237305, "random_agent_time": 0.0061495304107666016, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0007846355438232422, "random_agent_time": 0.0009205341339111328, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002241373062133789, "random_agent_time": 0.001965045928955078, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004982471466064453, "random_agent_time": 0.003026723861694336, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0029764175415039062, "random_agent_time": 0.002870798110961914, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0020220279693603516, "random_agent_time": 0.0029032230377197266, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023984909057617188, "random_agent_time": 0.001901865005493164, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004750728607177734, "random_agent_time": 0.002973318099975586, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002571582794189453, "random_agent_time": 0.0029070377349853516, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.004094123840332031, "random_agent_time": 0.0021238327026367188, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0029218196868896484, "random_agent_time": 0.002393007278442383, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0038595199584960938, "random_agent_time": 0.0022497177124023438, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.009995698928833008, "random_agent_time": 0.008544445037841797, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.005723237991333008, "random_agent_time": 0.005440473556518555, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.003440380096435547, "random_agent_time": 0.0033011436462402344, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005120992660522461, "random_agent_time": 0.006506681442260742, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002855539321899414, "random_agent_time": 0.002387523651123047, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0025980472564697266, "random_agent_time": 0.0015370845794677734, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003701925277709961, "random_agent_time": 0.003799915313720703, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005614042282104492, "random_agent_time": 0.0028514862060546875, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0053577423095703125, "random_agent_time": 0.002708911895751953, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00031757354736328125, "random_agent_time": 0.0006833076477050781, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002760648727416992, "random_agent_time": 0.003321409225463867, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002842426300048828, "random_agent_time": 0.002433300018310547, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.001651763916015625, "random_agent_time": 0.0019927024841308594, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002523660659790039, "random_agent_time": 0.0019609928131103516, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005426883697509766, "random_agent_time": 0.004549741744995117, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.0044209957122802734, "random_agent_time": 0.005233287811279297, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.008310317993164062, "random_agent_time": 0.0019359588623046875, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0052988529205322266, "random_agent_time": 0.0060880184173583984, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.010115861892700195, "random_agent_time": 0.008736371994018555, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00033402442932128906, "random_agent_time": 0.0007901191711425781, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003019094467163086, "random_agent_time": 0.0037200450897216797, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.001497030258178711, "random_agent_time": 0.0006968975067138672, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.003014087677001953, "random_agent_time": 0.0019953250885009766, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004734992980957031, "random_agent_time": 0.0022962093353271484, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004294633865356445, "random_agent_time": 0.002401590347290039, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002920866012573242, "random_agent_time": 0.002773284912109375, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.001984834671020508, "random_agent_time": 0.003202676773071289, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0026962757110595703, "random_agent_time": 0.002353191375732422, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0040895938873291016, "random_agent_time": 0.0023865699768066406, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026013851165771484, "random_agent_time": 0.005062580108642578, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003093719482421875, "random_agent_time": 0.0022840499877929688, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008012056350708008, "random_agent_time": 0.008045196533203125, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00487828254699707, "random_agent_time": 0.006611347198486328, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00455927848815918, "random_agent_time": 0.003016948699951172, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0031898021697998047, "random_agent_time": 0.0040738582611083984, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002167940139770508, "random_agent_time": 0.0019826889038085938, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004438638687133789, "random_agent_time": 0.005614757537841797, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002748727798461914, "random_agent_time": 0.002680063247680664, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002741098403930664, "random_agent_time": 0.002451181411743164, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00415492057800293, "random_agent_time": 0.002337932586669922, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0046155452728271484, "random_agent_time": 0.0024874210357666016, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002188444137573242, "random_agent_time": 0.002672910690307617, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0034580230712890625, "random_agent_time": 0.0021207332611083984, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0007603168487548828, "random_agent_time": 0.0008790493011474609, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026702880859375, "random_agent_time": 0.0026619434356689453, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004479408264160156, "random_agent_time": 0.0024309158325195312, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0033049583435058594, "random_agent_time": 0.0019402503967285156, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025713443756103516, "random_agent_time": 0.004459857940673828, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.00176239013671875, "random_agent_time": 0.002698659896850586, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003977060317993164, "random_agent_time": 0.0021669864654541016, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0050280094146728516, "random_agent_time": 0.002517223358154297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0038309097290039062, "random_agent_time": 0.002529621124267578, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0037221908569335938, "random_agent_time": 0.003488302230834961, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.005219221115112305, "random_agent_time": 0.00573277473449707, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002710103988647461, "random_agent_time": 0.0017614364624023438, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.005095720291137695, "random_agent_time": 0.002807140350341797, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002490997314453125, "random_agent_time": 0.004664421081542969, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.008461475372314453, "random_agent_time": 0.0021555423736572266, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004445075988769531, "random_agent_time": 0.0021369457244873047, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023488998413085938, "random_agent_time": 0.0022711753845214844, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004388570785522461, "random_agent_time": 0.005486011505126953, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003918170928955078, "random_agent_time": 0.001827239990234375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002311229705810547, "random_agent_time": 0.0020966529846191406, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.003032207489013672, "random_agent_time": 0.0030226707458496094, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023267269134521484, "random_agent_time": 0.001949310302734375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0042994022369384766, "random_agent_time": 0.0030317306518554688, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0048983097076416016, "random_agent_time": 0.0024089813232421875, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.002695322036743164, "random_agent_time": 0.0015857219696044922, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003462076187133789, "random_agent_time": 0.0025856494903564453, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022711753845214844, "random_agent_time": 0.002107858657836914, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004037380218505859, "random_agent_time": 0.0024805068969726562, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00032448768615722656, "random_agent_time": 0.0007395744323730469, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00505518913269043, "random_agent_time": 0.006723642349243164, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003907203674316406, "random_agent_time": 0.0017826557159423828, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.00475311279296875, "random_agent_time": 0.007513284683227539, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003066539764404297, "random_agent_time": 0.0030884742736816406, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0037908554077148438, "random_agent_time": 0.0019490718841552734, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002810239791870117, "random_agent_time": 0.002518892288208008, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0031766891479492188, "random_agent_time": 0.0016818046569824219, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004059553146362305, "random_agent_time": 0.0018856525421142578, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0029761791229248047, "random_agent_time": 0.0022461414337158203, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-l-m/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}]}